name: yoda_im
channels:
  - conda-forge
dependencies:
  - python=3.6
  - flask
  - flask-cors
  - xarray
  - geopandas
  - flake8
  - pytest
  - pip: 
    - git+https://github.com/cormorack/yodapy.git
